### ISSUE TITLE
A bunch of errors

### ISSUE THREAD

**Issue by Ziao** [MattMcFarland/sequelstore-connect#1]
Hi,

I tried to implement this, however I ran into a couple of issues.
First of all, this module is dependant on winston, which exists only  in the devDependencies (so it's not installed).
After that, I do (simplified):

``` javascript
DB = new Sequelize({/**/});
ExpressSession = require('express-session');
SequelizeStore = require('sequelstore-connect')(ExpressSession);
App.use(ExpressSession({
                store: new SequelizeStore(DB)
       })
);
```

And it spits out
`Unhandled rejection TypeError: undefined is not a function
    at SequelStore.applyProps (/node_modules/sequelstore-connect/lib/index.js:133:31)
    at new SequelStore (/node_modules/sequelstore-connect/lib/index.js:117:14)`

Am I doing something wrong or is there something wrong with the module?
Thanks,
Nick

**Comment by MattMcFarland** [comment]
There is something wrong with the module.  I'll try to fix it (but am bogged down with lots of other stuff unfortunately)
