### ISSUE TITLE
Deserializing session fails

### ISSUE THREAD

**Issue by SanityResort** [MattMcFarland/sequelstore-connect#2]
The module works fine to create new sessions in the database. But once you return to the site with an existing session cookie there is an error, causing the node process to exit.

```
TypeError: Cannot read property 'expires' of undefined
    at SequelStore.Store.createSession (D:\Development\projects\CheckShare\node_modules\express-session\session\store.js:90:28)
    at . (D:\Development\projects\CheckShare\node_modules\express-session\index.js:453:15)
```

I think the issue is, that the keys in the json string returned from the database is not correctly formatted:

`{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"passport":{"user":"926b37c4-8ef0-4893-8a71-f58664034512"}}`

While it should be like:

`{cookie:{"originalMaxAge":null,expires:null,httpOnly:true,path:"/"},passport:{user:"926b37c4-8ef0-4893-8a71-f58664034512"}}` (the keys are not quoted, which would allow the call `var expires = sess.cookie.expires` in express-session/session/store.js to work properly.

**Comment by blacksoil** [comment]
I hit the same issue. This is my fix:
https://github.com/MattMcFarland/sequelstore-connect/pull/3
